### ISSUE TITLE
Can't build on Visual Studio 2017 v15.8.9

### ISSUE THREAD

**Issue by TransientResponse** [nlohmann/json#1350]
- What is the issue you have?
Can't build project using json.hpp standalone or with vcpkg on Windows x64 with VS 2017 15.8.9

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
Try to build any project with `#include "json.hpp"`

- What is the expected behavior?
Build without errors

- And what is the actual behavior instead?
Build fails with these errors:
```
1>c:\users\[path]\json.hpp(918): error C2628: 'size_t' followed by 'unsigned' is illegal (did you forget a ';'?)
1>c:\users\[path]\json.hpp(918): error C2628: 'size_t' followed by 'char' is illegal (did you forget a ';'?)
1>c:\users\[path]\json.hpp(918): error C2886: 'size_t': symbol cannot be used in a member using-declaration
1>c:\users\[path]\build\src\predefined c++ types (compiler internal)(16): note: see declaration of 'size_t'
1>c:\users\[path]\json.hpp(921): error C2059: syntax error: 'type'
1>c:\users\[path]\json.hpp(11445): error C2628: 'uint8_t' followed by 'unsigned' is illegal (did you forget a ';'?)
1>c:\users\[path]\json.hpp(11501): note: see reference to class template instantiation 'nlohmann::detail::serializer<BasicJsonType>' being compiled
1>c:\users\[path]\json.hpp(11445): error C2628: 'uint8_t' followed by 'char' is illegal (did you forget a ';'?)
1>c:\users\[path]\json.hpp(11072): error C2760: syntax error: unexpected token 'char', expected 'type specifier'
1>c:\users\[path]\json.hpp(11467): error C2760: syntax error: unexpected token 'unsigned', expected 'expression'
```

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
Visual Studio 2017 v15.8.9 on Windows 10 1803
Visual C++ 2017   00369-60000-00001-AA083

- Did you use a released version of the library or the version from the `develop` branch?
Released v3.3.0 and vcpkg's 3.2.0

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
Instructions incomplete, I only get "test not available in configuration [*]" for anything I try in ctest.

**Comment by TransientResponse** [comment]
Nevermind, I had a define breaking things
