### ISSUE TITLE
Lib not working on ubuntu 16.04

### ISSUE THREAD

**Issue by rahulm-gdb** [nlohmann/json#905]
**Bug Report**

- What is the issue you have?
Cloned the repo and tried using json.hpp in my .cpp file.
Also tried disable debug assertions. with #define NDEBUG
- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?
Should compile and run normally.

- And what is the actual behavior instead?
Compile time error.error: 
static assertion failed: could not find to_json() method in T's namespace
         static_assert(sizeof(BasicJsonType) == 0
- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?
tried using both release as well as develop branch.
- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)? yes

**Feature Request**

- Describe the feature in as much detail as possible.

- Include sample usage where appropriate.

**Comment by nlohmann** [comment]
The compilation error indicates that you try to convert a type to `json` where the conversation could not be deduced by the library, for instance `myClass foo; json = foo;`. Without a more detailed error message and example code, I cannot analyze the issue.
