### ISSUE TITLE
cannot compile on ubuntu 18.04 and 16.04

### ISSUE THREAD

**Issue by chakpongchung** [nlohmann/json#1110]
- What is the issue you have?
```

#include <iostream>

using namespace std;
// #include <json.hpp>
#include <nlohmann/json.hpp>
using json = nlohmann::json;  // for convenience

int main() { cout << 0; }
```
```
sudo apt install nlohmann-json-dev  

g++ -std=c++11 main.cpp
```
```


In file included from test_json.cpp:6:0:
/usr/include/nlohmann/json.hpp: In function ‘bool nlohmann::operator<(nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::const_reference, nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::const_reference)’:
/usr/include/nlohmann/json.hpp:6057:62: error: wrong number of template arguments (1, should be 2)
                     return *lhs.m_value.array < *rhs.m_value.array;
                                                              ^~~~~
In file included from /usr/include/nlohmann/json.hpp:33:0,
                 from test_json.cpp:6:
/usr/include/c++/7/array:94:12: note: provided for ‘template<class _Tp, long unsigned int _Nm> struct std::array’
     struct array
            ^~~~~

```
- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
`
Linux ubuntu 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-16ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 

```

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
Related: #590

**Comment by nlohmann** [comment]
What version of the library are you using? This seems to be exactly the same issue as #590 which was fixed with version 3.0.0.

**Comment by nlohmann** [comment]
From the line number of the error, this seems to be version 2.1.1. This issue is a duplicate of #590 and fixed with 3.0.0.

**Comment by chakpongchung** [comment]
@nlohmann The problem is that:

`sudo apt install nlohmann-json-dev  ` installs the 2.x version

**Comment by nlohmann** [comment]
Please contact the maintainer of that package about this. I have no control over this.

**Comment by SunnyKatyara** [comment]
Dear nlohmann, i am unable to find "E: Unable to locate package nlohmann-json-dev". Its not available, can you please help me to figure it out.

Thank you

**Comment by nlohmann** [comment]
As I wrote above: I am not maintaining this package.
