### ISSUE TITLE
VS2017 implicit to std::string conversion fix.

### ISSUE THREAD

**Issue by qis** [nlohmann/json#464]
Hi! Great work so far. I had to patch the library to allow implicit to-string-conversions in VS2017.

```cpp
    template < typename ValueType, typename std::enable_if <
                   not std::is_pointer<ValueType>::value and
                   not std::is_same<ValueType, typename string_t::value_type>::value
//#ifndef _MSC_VER  // fix for issue #167 operator<< ambiguity under VS2015
                   and not std::is_same<ValueType, std::initializer_list<typename string_t::value_type>>::value
                   and not std::is_same<ValueType, typename std::string_view>::value
//#endif
                   , int >::type = 0 >
    operator ValueType() const
    {
        // delegate the call to get<>() const
        return get<ValueType>();
    }
```

Hope this helps.

**Comment by nlohmann** [comment]
@qis Could you please try the most recent version (f2dfa09aecf672a3b9980613bde196a5cb1ef994)?

**Comment by nlohmann** [comment]
My bad - I misunderstood your comment, so I reverted the last commit.

I cannot add the line with `std::string_view` to the code, because this would require C++17.

Could you please post the compiler error for the original code together with the options you are using with VS2017?

**Comment by qis** [comment]
Here are my tests with 1a6d7f5bca9baec12fe6065c6009903c24ea533f:

```cpp
#include <json.hpp>
#include <string>

int main(int argc, char* argv[]) {
  using json = nlohmann::json;
  json v  = "test";
  std::string test;
  test = v;
  return 0;
}
```

Compiled with `/permissive- /std:c++latest /utf-8` it yields this error:

```
1>main.cpp
1>C:\Workspace\test\src\main.cpp(8): error C2593: 'operator =' is ambiguous
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.24930\include\xstring(2254): note: could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(const _Elem)'
1>        with
1>        [
1>            _Elem=char
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.24930\include\xstring(2249): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(const _Elem *const )'
1>        with
1>        [
1>            _Elem=char
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.24930\include\xstring(2243): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(const std::basic_string_view<char,std::char_traits<char>>)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.24930\include\xstring(2221): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.24930\include\xstring(2184): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::initializer_list<_Elem>)'
1>        with
1>        [
1>            _Elem=char
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.24930\include\xstring(2072): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&) noexcept(<expr>)'
1>C:\Workspace\test\src\main.cpp(8): note: while trying to match the argument list '(std::string, json)'
```

I propose this change:

```cpp
    template < typename ValueType, typename std::enable_if <
                   not std::is_pointer<ValueType>::value and
                   not std::is_same<ValueType, typename string_t::value_type>::value
#if !defined(_MSC_VER) || _MSC_VER > 1900  // fix for issue #167 operator<< ambiguity under VS2015
                   and not std::is_same<ValueType, std::initializer_list<typename string_t::value_type>>::value
#endif
#if defined(_MSC_VER) && defined(_HAS_CXX17)
                   and not std::is_same<ValueType, typename std::string_view>::value
#endif
                   , int >::type = 0 >
    operator ValueType() const
    {
        // delegate the call to get<>() const
        return get<ValueType>();
    }
```

The `_HAS_CXX17` preprocessor definition is used in `<string_view>` from Microsoft.

**Comment by theodelrieu** [comment]
I shall install VS2017 and investigate that bug, we cannot put `string_view` in the library unfortunately.

Thanks for the report!

**Comment by nlohmann** [comment]
Thanks for the feedback. This seems to be an MSVC bug, since the code compiles with earlier versions and C++17 should not break C++11 code.

**Comment by theodelrieu** [comment]
I'm not sure there is a good way to fix this problem, #144 fixed a similar issue, by removing the possibility to convert `basic_json` to `char` (#276).

If I understood correctly the other issues, this problem will arise whenever a class with several `operator=` is used on the left-hand side of `operator=` (I don't think this is a bug of the library, if I'm wrong, please tell me)

To me, #144 was not a good fix, for the reason mentioned above, thus I don't want to do the same thing.
However, to workaround this problem, you can still use:

- implicit conversion by calling constructor (`std::string s = j;`)
- `get`: `s = j.get<std::string>();`
- `static_cast` the right-hand side of `operator=`

That might not suit your needs, but I really don't know if there's a way to workaround that without removing features like in #144 

We should mention this problem in the README, since this might come up again, even with user-defined types.

**Comment by nlohmann** [comment]
FYI: The library is now also checked with MSVC 19.10.25017.0 / Build Engine version 15.1.548.43366 at AppVeyor, see https://ci.appveyor.com/project/nlohmann/json.

**Comment by nlohmann** [comment]
@qis I added the code you posted in https://github.com/nlohmann/json/issues/464#issuecomment-281160071 as regression test (https://github.com/nlohmann/json/commit/b4dbebffcdb98c91130133adb6583a1b5dafe6a6). It succeeds with MSVC 2015 and 2017 in [AppVeyor](https://ci.appveyor.com/project/nlohmann/json/build/1850).

Can I close this ticket?

**Comment by xnetsystems** [comment]
@nlohmann Great! May I have until evening (UTC) to test it? Just in case I find a related problem.

**Comment by xnetsystems** [comment]
@nlohmann Great! May I have until evening (UTC) to test it? Just in case I find a related problem.

**Comment by qis** [comment]
@nlohmann Great! May I have until evening (UTC) to test it? Just in case I find a related problem.

**Comment by nlohmann** [comment]
Of course!

**Comment by qis** [comment]
@nlohmann Ok, it works fine (like before) if there is no `/std:c++latest` compiler option present. It still requires my changes for a C++17 enabled build.

Here is a complete project for the minimal example: https://github.com/qis/json

P.S.: Just noticed that `_HAS_CXX17` is always defined as `0` if C++17 is disabled or `1` if it is enabled. Updated `json-c2e80a7-fixed.hpp`.

**Comment by nlohmann** [comment]
Sorry, I misunderstood. I shall add your fix. I also need to add a c++latest build to AppVeyor.

**Comment by nlohmann** [comment]
@qis I am neither expert with MSVC not with CMake. Could you give me a hint how to pass `/std:c++latest` to the build via cmake? Then I can add it to the AppVeyor build matrix.

**Comment by qis** [comment]
@nlohmann You can just add it to `CMAKE_CXX_FLAGS`: https://github.com/qis/json/blob/master/CMakeLists.txt#L11

**Comment by nlohmann** [comment]
Ok, got it. AppVeyor now has a configuration where MSVC 2017 is executed with the mentioned flags: https://ci.appveyor.com/project/nlohmann/json/build/1882/job/xmj9j1tlga6eeh46

Next stop: adding the fix ;)

**Comment by nlohmann** [comment]
Unfortunately, the proposed fix does not work, see https://github.com/nlohmann/json/commit/628be157a27f71b4f045fc687d723f9e1bbdfc51 and https://ci.appveyor.com/project/nlohmann/json/build/1884. It seems as if `_HAS_CXX17` is also defined with MSVC 2015 and also with MSVC 2017 without defining `/std:c++latest`. Consequently, we get the error

```
C:\projects\json\src\json.hpp(3734): error C2039: 'string_view': is not a member of 'std' [C:\projects\json\test\json_unit.vcxproj]
```

I have to find a better way to check whether `std::string_view` exists.

**Comment by nlohmann** [comment]
Ok, it's insufficient to just check whether `_HAS_CXX17` is defined: it also has to have the value `1`. This works now: https://github.com/nlohmann/json/commit/e48114bbd6625e6199baa10cbfe783bb95c32604.

@qis, could you check for yourself whether this works? Then I can merge the feature branch.

**Comment by qis** [comment]
@nlohmann Seems to work fine in both, VS2017 and clang 4.0.0 in C++17 mode. Thank you very much for this change!

**Comment by nlohmann** [comment]
Merged the feature branch. Thanks for reporting and helping out so patiently!

**Comment by lethe555** [comment]
doesn't work in VS2015.3 ,with /std:c++latest

**Comment by nlohmann** [comment]
Could you provide an error message and the exact version?

**Comment by lethe555** [comment]
json.hpp(3734): error C2039: 'string_view': is not a member of 'std'
in VS2015  with /std:c++latest ,_HAS_CXX17 has value of 1

**Comment by qis** [comment]
@lethe555 The `_MSC_VER > 1900` code you pasted fixes the problem, correct?

**Comment by lethe555** [comment]
@qis YES .

**Comment by nlohmann** [comment]
I'll have a look.

**Comment by nlohmann** [comment]
@lethe555 I added your proposed fix. Could you please check if it works for you?

**Comment by lethe555** [comment]
@nlohmann It works well now.

**Comment by nlohmann** [comment]
Cool, thanks!
