### ISSUE TITLE
xwidgets doesn't compile with version >3.10.3

### ISSUE THREAD

**Issue by dimitry-ishenko** [nlohmann/json#3602]
### Description

The [xwidgets](https://github.com/jupyter-xeus/xwidgets) project, which uses this library stopped compiling after version 3.10.3. Specifically, commit 0e694b4060ed55df980eaaebc2398b0ff24530d4 is responsible for the problem.

Even more specifically, redefinition of `is_constructible_string_type` from this:

https://github.com/nlohmann/json/blob/aa0e847e5b57a00696bdcb6a834b927231b81613/include/nlohmann/detail/meta/type_traits.hpp#L331-L348

to this:

https://github.com/nlohmann/json/blob/0e694b4060ed55df980eaaebc2398b0ff24530d4/include/nlohmann/detail/meta/type_traits.hpp#L319-L325

is what's causing the error.

The exact part of `xwidgets` where the error happens is [here](https://github.com/jupyter-xeus/xwidgets/blob/a0fac3628b40ec916b2350c8eb3794750b519326/include/xwidgets/xcommon.hpp#L43-L47):

```c++
    template <class T>
    inline void xwidgets_deserialize(T& value, const nl::json& j, const xeus::buffer_sequence&)
    {
        value = j.template get<T>();
    }
```

I know `xwidgets` says that they are only compatible with `json` version <3.10, but most up-to-date linux distros only supply 3.10.5. Plus, everything used to work up until the above commit.

### Reproduction steps

1. Install `xeus-dev` and `xproperty-dev` dependencies from my [ppa:ppa-verse/cling](https://launchpad.net/~ppa-verse/+archive/ubuntu/cling) repo.

2. Download and unpack: [xwidgets_0.26.1.orig.tar.gz](https://github.com/nlohmann/json/files/9174348/xwidgets_0.26.1.orig.tar.gz)

3. Download (remove .txt) and unpack **inside** `xwidgets-0.26.1` above: [xwidgets_0.26.1-0ppa2.debian.tar.xz.txt](https://github.com/nlohmann/json/files/9174350/xwidgets_0.26.1-0ppa2.debian.tar.xz.txt)

4. Execute `dpkg-buildpackage -uc -us -b`

### Expected vs. actual results

Expected: Successful compilation and creation of `xwidgets` debian package.

Actual: Failed compilation. (See error messages below and attached build log).

[buildlog_ubuntu-jammy-amd64.xwidgets_0.26.1-0ppa2_ubuntu22.04_BUILDING.zip](https://github.com/nlohmann/json/files/9174397/buildlog_ubuntu-jammy-amd64.xwidgets_0.26.1-0ppa2_ubuntu22.04_BUILDING.zip)

### Error messages

```Shell
In file included from /root/xwidgets/include/xwidgets/xaudio.hpp:16,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xmaterialize.hpp: In instantiation of 'xw::xmaterialize<B, P>::xmaterialize(bool, A&& ...) [with A = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; B = xw::xlayout; P = {}]':
/root/xwidgets/include/xwidgets/xmaterialize.hpp:66:55:   required from 'xw::xmaterialize<B, P>::xmaterialize(A&& ...) [with A = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; B = xw::xlayout; P = {}]'
/usr/include/nlohmann/detail/conversions/from_json.hpp:111:7:   required from 'void nlohmann::detail::from_json(const BasicJsonType&, ConstructibleStringType&) [with BasicJsonType = nlohmann::basic_json<>; ConstructibleStringType = xw::xmaterialize<xw::xlayout>; typename std::enable_if<(nlohmann::detail::is_constructible_string_type<BasicJsonType, ConstructibleStringType>::value && (! std::is_same<typename BasicJsonType::string_t, ConstructibleStringType>::value)), int>::type <anonymous> = 0]'
/usr/include/nlohmann/detail/conversions/from_json.hpp:470:25:   required from 'decltype (nlohmann::detail::from_json(j, forward<T>(val))) nlohmann::detail::from_json_fn::operator()(const BasicJsonType&, T&&) const [with BasicJsonType = nlohmann::basic_json<>; T = xw::xmaterialize<xw::xlayout>&; decltype (nlohmann::detail::from_json(j, forward<T>(val))) = void]'
/usr/include/nlohmann/adl_serializer.hpp:33:30:   required from 'static decltype ((nlohmann::{anonymous}::from_json(forward<BasicJsonType>(j), val), void())) nlohmann::adl_serializer<T, SFINAE>::from_json(BasicJsonType&&, TargetType&) [with BasicJsonType = const nlohmann::basic_json<>&; TargetType = xw::xmaterialize<xw::xlayout>; ValueType = xw::xmaterialize<xw::xlayout>; <template-parameter-1-2> = void; decltype ((nlohmann::{anonymous}::from_json(forward<BasicJsonType>(j), val), void())) = void]'
/usr/include/nlohmann/json.hpp:3073:45:   required from 'ValueType nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::get_impl(nlohmann::detail::priority_tag<0>) const [with ValueType = xw::xmaterialize<xw::xlayout>; typename std::enable_if<(nlohmann::detail::is_default_constructible<ValueType>::value && nlohmann::detail::has_from_json<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>, ValueType>::value), int>::type <anonymous> = 0; ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; BinaryType = std::vector<unsigned char>]'
/usr/include/nlohmann/json.hpp:3216:35:   required from 'constexpr decltype (declval<const basic_json_t&>().get_impl<ValueType>(nlohmann::detail::priority_tag<4>{})) nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::get() const [with ValueTypeCV = xw::xmaterialize<xw::xlayout>; ValueType = xw::xmaterialize<xw::xlayout>; ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; BinaryType = std::vector<unsigned char>; decltype (declval<const basic_json_t&>().get_impl<ValueType>(nlohmann::detail::priority_tag<4>{})) = xw::xmaterialize<xw::xlayout>; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::basic_json_t = nlohmann::basic_json<>]'
/root/xwidgets/include/xwidgets/xcommon.hpp:46:34:   required from 'void xw::xwidgets_deserialize(T&, const json&, const buffer_sequence&) [with T = xw::xmaterialize<xw::xlayout>; nlohmann::json = nlohmann::basic_json<>; xeus::buffer_sequence = std::vector<std::vector<char> >]'
/root/xwidgets/include/xwidgets/xtransport.hpp:37:33:   required from 'void xw::set_property_from_patch(P&, const json&, const buffer_sequence&) [with P = xp::xproperty<xw::xmaterialize<xw::xlayout>, xw::xmaterialize<xw::xaudio> >; nlohmann::json = nlohmann::basic_json<>; xeus::buffer_sequence = std::vector<std::vector<char> >]'
/root/xwidgets/include/xwidgets/xwidget.hpp:73:32:   required from 'void xw::xwidget<D>::apply_patch(const json&, const buffer_sequence&) [with D = xw::xmaterialize<xw::xaudio>; nlohmann::json = nlohmann::basic_json<>; xeus::buffer_sequence = std::vector<std::vector<char> >]'
/root/xwidgets/include/xwidgets/xmedia.hpp:68:31:   required from 'void xw::xmedia<D>::apply_patch(const json&, const buffer_sequence&) [with D = xw::xmaterialize<xw::xaudio>; nlohmann::json = nlohmann::basic_json<>; xeus::buffer_sequence = std::vector<std::vector<char> >]'
/root/xwidgets/include/xwidgets/xaudio.hpp:71:31:   required from 'void xw::xaudio<D>::apply_patch(const json&, const buffer_sequence&) [with D = xw::xmaterialize<xw::xaudio>; nlohmann::json = nlohmann::basic_json<>; xeus::buffer_sequence = std::vector<std::vector<char> >]'
/root/xwidgets/include/xwidgets/xtransport.hpp:192:45:   required from 'void xw::xtransport<D>::handle_message(const xeus::xmessage&) [with D = xw::xmaterialize<xw::xaudio>]'
/root/xwidgets/src/xaudio.cpp:10:33:   required from here
/root/xwidgets/include/xwidgets/xmaterialize.hpp:74:69: error: no matching function for call to 'xw::xlayout<xw::xmaterialize<xw::xlayout> >::xlayout(const std::__cxx11::basic_string<char>&)'
   74 |         : base_type(std::forward<A>(args)...), m_generator(generator)
      |                                                                     ^
In file included from /root/xwidgets/include/xwidgets/xobject.hpp:18,
                 from /root/xwidgets/include/xwidgets/xlayout.hpp:16,
                 from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xtransport.hpp:132:12: note: candidate: 'xw::xtransport<D>::xtransport(xw::xtransport<D>&&) [with D = xw::xmaterialize<xw::xlayout>]'
  132 |     inline xtransport<D>::xtransport(xtransport&& other)
      |            ^~~~~~~~~~~~~
In file included from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   inherited here
   65 |         using base_type::base_type;
      |                          ^~~~~~~~~
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
In file included from /root/xwidgets/include/xwidgets/xobject.hpp:18,
                 from /root/xwidgets/include/xwidgets/xlayout.hpp:16,
                 from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xtransport.hpp:124:12: note: candidate: 'xw::xtransport<D>::xtransport(const xw::xtransport<D>&) [with D = xw::xmaterialize<xw::xlayout>]'
  124 |     inline xtransport<D>::xtransport(const xtransport& other)
      |            ^~~~~~~~~~~~~
In file included from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   inherited here
   65 |         using base_type::base_type;
      |                          ^~~~~~~~~
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
In file included from /root/xwidgets/include/xwidgets/xobject.hpp:18,
                 from /root/xwidgets/include/xwidgets/xlayout.hpp:16,
                 from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xtransport.hpp:113:12: note: candidate: 'xw::xtransport<D>::xtransport(xeus::xcomm&&, bool) [with D = xw::xmaterialize<xw::xlayout>]'
  113 |     inline xtransport<D>::xtransport(xeus::xcomm&& comm, bool owning)
      |            ^~~~~~~~~~~~~
In file included from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   inherited here
   65 |         using base_type::base_type;
      |                          ^~~~~~~~~
In file included from /root/xwidgets/include/xwidgets/xobject.hpp:18,
                 from /root/xwidgets/include/xwidgets/xlayout.hpp:16,
                 from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xtransport.hpp:113:52: note:   no known conversion for argument 1 from 'const std::__cxx11::basic_string<char>' to 'xeus::xcomm&&'
  113 |     inline xtransport<D>::xtransport(xeus::xcomm&& comm, bool owning)
      |                                      ~~~~~~~~~~~~~~^~~~
In file included from /root/xwidgets/include/xwidgets/xlayout.hpp:16,
                 from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xobject.hpp:27:11: note: candidate: 'xw::xobject<xw::xmaterialize<xw::xlayout> >::xobject(const xw::xobject<xw::xmaterialize<xw::xlayout> >&)'
   27 |     class xobject : public xtransport<D>
      |           ^~~~~~~
In file included from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   inherited here
   65 |         using base_type::base_type;
      |                          ^~~~~~~~~
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
In file included from /root/xwidgets/include/xwidgets/xlayout.hpp:16,
                 from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xobject.hpp:27:11: note: candidate: 'xw::xobject<xw::xmaterialize<xw::xlayout> >::xobject(xw::xobject<xw::xmaterialize<xw::xlayout> >&&)'
   27 |     class xobject : public xtransport<D>
      |           ^~~~~~~
In file included from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   inherited here
   65 |         using base_type::base_type;
      |                          ^~~~~~~~~
/root/xwidgets/include/xwidgets/xlayout.hpp:65:26: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
/root/xwidgets/include/xwidgets/xlayout.hpp:139:12: note: candidate: 'xw::xlayout<D>::xlayout() [with D = xw::xmaterialize<xw::xlayout>]'
  139 |     inline xlayout<D>::xlayout()
      |            ^~~~~~~~~~
/root/xwidgets/include/xwidgets/xlayout.hpp:139:12: note:   candidate expects 0 arguments, 1 provided
In file included from /root/xwidgets/include/xwidgets/xwidget.hpp:15,
                 from /root/xwidgets/include/xwidgets/xmedia.hpp:18,
                 from /root/xwidgets/include/xwidgets/xaudio.hpp:17,
                 from /root/xwidgets/src/xaudio.cpp:1:
/root/xwidgets/include/xwidgets/xlayout.hpp:25:11: note: candidate: 'xw::xlayout<xw::xmaterialize<xw::xlayout> >::xlayout(const xw::xlayout<xw::xmaterialize<xw::xlayout> >&)'
   25 |     class xlayout : public xobject<D>
      |           ^~~~~~~
/root/xwidgets/include/xwidgets/xlayout.hpp:25:11: note:   no known conversion for argument 1 from 'const std::__cxx11::basic_string<char>' to 'const xw::xlayout<xw::xmaterialize<xw::xlayout> >&'
/root/xwidgets/include/xwidgets/xlayout.hpp:25:11: note: candidate: 'xw::xlayout<xw::xmaterialize<xw::xlayout> >::xlayout(xw::xlayout<xw::xmaterialize<xw::xlayout> >&&)'
/root/xwidgets/include/xwidgets/xlayout.hpp:25:11: note:   no known conversion for argument 1 from 'const std::__cxx11::basic_string<char>' to 'xw::xlayout<xw::xmaterialize<xw::xlayout> >&&'
make[3]: *** [CMakeFiles/xwidgets-static.dir/build.make:93: CMakeFiles/xwidgets-static.dir/src/xaudio.cpp.o] Error 1
```

### Compiler and operating system

Ubuntu 22.04, gcc 11.2.0

### Library version

v3.10.3 + 0e694, v3.10.5, develop

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [x] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
I can reproduce the issue and trace it back to the same `get()` call in `xwidgets/xcommon.hpp`. I have a band-aid in mind but it might cause more breakage.

**Comment by dimitry-ishenko** [comment]
@falbrechtskirchinger is this a band-aid for `json` or for `xwidgets`? Ideally it would be for `xwidgets` so I don't have to package my own patched `json` version.

**Comment by falbrechtskirchinger** [comment]
For `json`. I don't see an easy way of working around it in `xwidgets`. Unit tests are succeeding so far.

**Comment by dimitry-ishenko** [comment]
@falbrechtskirchinger also if you don't mind, I'd like to understand what's going on in here and why it's causing the error.

**Comment by falbrechtskirchinger** [comment]
The issue is this `xmaterialize` constructor which erroneously identifies `xmaterialize` as a `StringType`.

```cpp
    template <template <class> class B, class... P>
    template <class... A>
    inline xmaterialize<B, P...>::xmaterialize(A&&... args)
        : xmaterialize(false, std::forward<A>(args)...)
    {
    }
```

The band-aid consists of re-adding the check for a `value_type` member typedef/using alias. That doesn't uniquely identify `StringType`s either but is better than the current state.

I've started a discussion (#3603) to try and fix issues like this one in 4.0.

**Comment by dimitry-ishenko** [comment]
@falbrechtskirchinger thank you, I understand now.

As a workaround, what if I replaced `j.template get<T>()` with a fully specialized version of whatever function it calls?

**Comment by dimitry-ishenko** [comment]
... or I supposed I can roll my own version with your _fresh-off-the-press_ patch, since you are so fast. 🥇 🥇 🥇

**Comment by falbrechtskirchinger** [comment]
You could try calling `nlohmann::from_json(const nlohmann:: json &, T &)` directly but I'm not sure that's going to work.

Grabbing my patch is likely going to be more fruitful.

**Comment by dimitry-ishenko** [comment]
OK I will try both. Thank you for such a fast response. 😃

**Comment by falbrechtskirchinger** [comment]
Well, unless I'm not using the correct header, it's not actually working. :-(

**Comment by dimitry-ishenko** [comment]
@falbrechtskirchinger yep, I can confirm that neither of the methods worked for me.

**Comment by dimitry-ishenko** [comment]
@falbrechtskirchinger FWIW if I patch `v3.10.5` with your patch it works fine...

**Comment by dimitry-ishenko** [comment]
Commit 261cc4e509c51d53c57d0c266abd4a78f134e6a4 is the other culprit that's causing the problem on the `develop` branch:

```diff
diff --git a/include/nlohmann/detail/conversions/from_json.hpp b/include/nlohmann/detail/conversions/from_json.hpp
index 207d3e3024..cc06f198b4 100644
--- a/include/nlohmann/detail/conversions/from_json.hpp
+++ b/include/nlohmann/detail/conversions/from_json.hpp
@@ -105,13 +105,12 @@ void from_json(const BasicJsonType& j, typename BasicJsonType::string_t& s)
 }
 
 template <
-    typename BasicJsonType, typename ConstructibleStringType,
+    typename BasicJsonType, typename StringType,
     enable_if_t <
-        is_constructible_string_type<BasicJsonType, ConstructibleStringType>::value&&
-        !std::is_same<typename BasicJsonType::string_t,
-                      ConstructibleStringType>::value,
-        int > = 0 >
-void from_json(const BasicJsonType& j, ConstructibleStringType& s)
+        std::is_assignable<StringType&, const typename BasicJsonType::string_t>::value
+        && !std::is_same<typename BasicJsonType::string_t, StringType>::value
+        && !is_json_ref<StringType>::value, int > = 0 >
+void from_json(const BasicJsonType& j, StringType& s)
 {
     if (JSON_HEDLEY_UNLIKELY(!j.is_string()))
     {
```

**Comment by falbrechtskirchinger** [comment]
Thanks for confirming. I already suspected that it might very well work with 3.10.5.

Several issues caused by 0e694b4 were addressed in the 3.11.0 development cycle, and there were bound to be some mistakes.

**Comment by falbrechtskirchinger** [comment]
Adding the same `value_type` check makes `xwidgets` compile with `develop`. :-)

**Comment by dimitry-ishenko** [comment]
Thanks @falbrechtskirchinger. I ended up throwing a patched version of `nlohmann-json3` in my [PPA](https://launchpad.net/~ppa-verse/+archive/ubuntu/cling) for now and had to do a bit of version dependency gymnastics in `xwidgets`.

Once 3.11 is out, I will undo all that.

Thank you for you help. 🎩 🎩 🎩

**Comment by falbrechtskirchinger** [comment]
It's not breaking existing code. We're going back to the method in 3.10.5. I don't really like it, but are proper solution requires a bit more thought. Basically, we need some trait that users are allowed to specialize for custom types.

Related discussion post: #3603
