### ISSUE TITLE
explicit constructor with default does not compile

### ISSUE THREAD

**Issue by bpmckinnon** [nlohmann/json#3077]
From include/nlohmann/json.hpp
![image](https://user-images.githubusercontent.com/4360155/137010716-8beee739-e242-41f2-8f2e-799e46483f16.png)
The change from ValueType ret; to ValueType ret{}; is causing a compiler error for the construction of a type with an explicit default constructor of the form.

explicit Foo(const alloc_context& allocContext = alloc_context())

In vs2019 it gives the following errors, using c++17
error C2512: '###': no appropriate default constructor available
note: Constructor for class '###' is declared 'explicit'

This is happening in a from_json call to my custom container type

Worked in 3.9.1, does not work in 3.10.2

**Comment by nlohmann** [comment]
I can confirm the issue with Xcode on macOS, so it's not an MSVC issue.

**Comment by nlohmann** [comment]
In fact, this is the Clang-Tidy warning that led to the (breaking) change:

```
error: uninitialized record type: 'ret' [cppcoreguidelines-pro-type-member-init,hicpp-member-init,-warnings-as-errors]
        ValueType ret;
        ^
                     {}
´´`
