### ISSUE TITLE
From Version 2.1.1 to 3.6.1 serialize std::set

### ISSUE THREAD

**Issue by MattiasEppler** [nlohmann/json#1676]
I upgraded to version 3.6.1 until this I serialized a std::set in this way
```

class Settings
{
  std::set<MetaData> Clients{};
}

inline void to_json(json& j, const Settings& settings)
{
        j = json
        {
            { "clients", settings.Clients },
        };
}

inline void from_json(const json& j, Settings& settings)
{
        auto clients = j.at("clients").get<vector<MetaData>>();

        for (const auto& client : clients)
        {
            settings.Clients.insert(client);
        }
}
```

Now I get the errors:

 Error C2440: 'initializing': cannot convert from 'initializer list' to 'nlohmann::json' (142)
    Error C2672: 'nlohmann::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::adl_serializer>::get': no matching overloaded function found (160)

**Comment by MattiasEppler** [comment]
It is not only the std::set. Its a problem with serialiize std containers.
I switched my project back to 3.0.1.
The code above is working in this version. So we can change the label from question to bug.

**Comment by nlohmann** [comment]
The example is incomplete (there is code missing, and there are syntax errors). Could you please provide a small example that does compile with 2.1.1?

**Comment by MattiasEppler** [comment]
Sorry. Complete example:
The enum is commented out. So the example works in 3.0.1.

`namespace pdx
{
    using nlohmann::json;
    using namespace std;

    //enum class CyclicErrorAction
    //{
    //    None,
    //    Stop,
    //    StopAll
    //};

    //
    //NLOHMANN_JSON_SERIALIZE_ENUM( CyclicErrorAction, 
    //{
    //    { CyclicErrorAction::None, "None"},
    //    { CyclicErrorAction::Stop, "Stop"},
    //    { CyclicErrorAction::StopAll, "StopAll"},  
    //})

    class MetaData
    {
    public:

        string Name;
    };


    class Settings
    {
            
    public:

        //CyclicErrorAction OnCyclicError = CyclicErrorAction::None;
        
        bool ShowAdditionalTrace = false;
        std::string Source;
        std::set<MetaData> Clients{};

        
    };
        
    inline void to_json(json& j, const Settings& settings)
    {
        j = json
        {
            //{ "onCyclicError", settings.OnCyclicError },
            { "showAdditionalTrace", settings.ShowAdditionalTrace },
            { "clients", settings.Clients },
            { "source", settings.Source },
            
        };
    }

    inline void from_json(const json& j, Settings& settings)
    {
        //settings.OnCyclicError = j.at("onCyclicError").get<decltype(settings.OnCyclicError)>();
        settings.ShowAdditionalTrace = j.at("showAdditionalTrace").get<decltype(settings.ShowAdditionalTrace)>();
        settings.Source = j.at("source").get<decltype(settings.Source)>();
        
        auto clients = j.at("clients").get<std::vector<MetaData>>();

        for (const auto& client : clients)
        {
            settings.Clients.insert(client);
        }
    }

    inline void to_json(json& j, const MetaData& metaData)
    {
        j["name"] = metaData.Name;

    }

    inline void from_json(const json& j, MetaData& metaData)
    {
        metaData.Name = j.at("name").get<decltype(metaData.Name)>();
    }
}

using namespace pdx;

int main()
{
    std::cout << "Start!\n";

    Settings settings {};

    const auto j = json(settings);

    const auto s =  j.get<Settings>();
}`

**Comment by nlohmann** [comment]
This code compiles with Xcode 10.3 with the `develop` version. I had to make two changes:

1. Move the `from_json`/`to_json` methods for `MetaData` up above their first use in the `from_json` method for `Settings`.
2. Add a comparison operator for `MetaData` to use it in a `std::set`.

I am not sure why this code would have compiled in earlier versions.

```cpp
#include "json.hpp"

#include <set>
#include <iostream>

using nlohmann::json;
using namespace std;

namespace pdx
{
    using nlohmann::json;
    using namespace std;
    
    //enum class CyclicErrorAction
    //{
    //    None,
    //    Stop,
    //    StopAll
    //};
    
    //
    //NLOHMANN_JSON_SERIALIZE_ENUM( CyclicErrorAction,
    //{
    //    { CyclicErrorAction::None, "None"},
    //    { CyclicErrorAction::Stop, "Stop"},
    //    { CyclicErrorAction::StopAll, "StopAll"},
    //})
    
    class MetaData
    {
    public:
        string Name;
        friend bool operator<(const MetaData& a, const MetaData& b) { return a.Name < b.Name; }
    };
    
    inline void to_json(json& j, const MetaData& metaData)
    {
        j["name"] = metaData.Name;
        
    }
    
    inline void from_json(const json& j, MetaData& metaData)
    {
        metaData.Name = j.at("name").get<decltype(metaData.Name)>();
    }

    class Settings
    {
        
    public:
        
        //CyclicErrorAction OnCyclicError = CyclicErrorAction::None;
        
        bool ShowAdditionalTrace = false;
        std::string Source;
        std::set<MetaData> Clients{};
        
        
    };
    
    inline void to_json(json& j, const Settings& settings)
    {
        j = json
        {
            //{ "onCyclicError", settings.OnCyclicError },
            { "showAdditionalTrace", settings.ShowAdditionalTrace },
            { "clients", settings.Clients },
            { "source", settings.Source },
            
        };
    }
    
    inline void from_json(const json& j, Settings& settings)
    {
        //settings.OnCyclicError = j.at("onCyclicError").get<decltype(settings.OnCyclicError)>();
        settings.ShowAdditionalTrace = j.at("showAdditionalTrace").get<decltype(settings.ShowAdditionalTrace)>();
        settings.Source = j.at("source").get<decltype(settings.Source)>();
        
        auto clients = j.at("clients").get<std::vector<MetaData>>();
        
        for (const auto& client : clients)
        {
            settings.Clients.insert(client);
        }
    }
}

using namespace pdx;

int main()
{
    std::cout << "Start!\n";
    
    Settings settings {};
    
    const auto j = json(settings);
    
    const auto s =  j.get<Settings>();
}
```

**Comment by MattiasEppler** [comment]
Hi, oh so the order was the only problem. :cry: 
The operator < is implemented in my real project. I just removed it in my sample for simplicity. In  2.1.1 it was working without the operator.

Thanks for your quick help.
