### PR TITLE
Fix merge_patch shadow warning

### LINKED ISSUE #1339: Shadowed Member in merge_patch
- What is the issue you have?

Compiling in downstream projects with `-Wshadow` warns on `void merge_patch(const basic_json& patch)` shadowing a member of `this`.

https://github.com/nlohmann/json/blob/master/include/nlohmann/json.hpp#L7866

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

Compile with Clang 5.0.0 and `CXXFLAGS="-Wshadow"`.

- What is the expected behavior?

Better not to shadow a member of `this` :)

- And what is the actual behavior instead?

Throws a warning, e.g.: https://travis-ci.org/openPMD/openPMD-api/jobs/449795263

```
single_include/nlohmann/json.hpp:
In member function ‘void nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::merge_patch(const nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>&)’:
single_include/nlohmann/json.hpp:20126:5: error: declaration of ‘patch’ shadows a member of 'this' [-Werror=shadow]
     {
```

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

Clang 5.0.0 on Travis CI (Ubuntu 14.04)

- Did you use a released version of the library or the version from the `develop` branch?

We use release 3.4.0.

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

N/A

first seen by @franzpoeschel

### PR DESCRIPTION
**Pull request by ax3l**
Fix `-Wshadow` warning in public header function `merge_patch`.
Close #1339 

Avoid shadowing a member of `this` (member function `patch`) by choosing the same name as parameter (`-Wshadow`). Instead, make name of parameter more expressive.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [ ]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

### CODE REVIEW

**Comment by nlohmann** [comment]
Thanks!
