### ISSUE TITLE
Illegal indirection

### ISSUE THREAD

**Issue by brunohkbx** [nlohmann/json#467]
I'm trying to use it in VS2015 but when I try to compile I got this error.

C2100 Illegal indirection

**Comment by nlohmann** [comment]
This is strange, because the project compiles with AppVeyor without problems:

- Project: https://ci.appveyor.com/project/nlohmann/json
- Config file: https://github.com/nlohmann/json/blob/develop/appveyor.yml

What is the exact error message? What compilation flags are you using?

**Comment by brunohkbx** [comment]
I just updated my VS2015 and its working fine.
Thanks!

**Comment by glennra** [comment]
I have this issue too.
c:\path\to\json.hpp(887): error C2100: illegal indirection
c:\path\to\json.hpp(898): note: see reference to class template instantiation 'nlohmann::detail::static_const<nlohmann::detail::to_json_fn>' being compiled

Compilation flags generated by CMake:
/Yu"StdAfx.h" /GS /TP /W3 /Zc:wchar_t /I"C:\Boost\include\boost-1_60" <other include paths removed> /Zi /Gm- /Od /Ob0 /Fd"MyLib.dir\Debug\MyLib.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "_DEBUG" /D "BOOST_LOG_DYN_LINK" /D "BOOST_USE_WINAPI_VERSION=0x0601" /D "CMAKE_INTDIR=\"Debug\"" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /GR /Gd /MDd /Fa"Debug/" /EHsc /nologo /Fo"MyLib.dir\Debug\" /Fp"MyLib.dir\Debug\MyLib.pch"

**Comment by nlohmann** [comment]
@glennra The tests at AppVeyor work with MSVC 14.0.25420.1 (see https://ci.appveyor.com/project/nlohmann/json for detailed output). I'm not sure about the differences to the version you are using, but @brunohkbx seems to have fixed the issue by updating.

**Comment by glennra** [comment]
Thanks. It works with:
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3

VS usually automatically offers updates but in this case it had not done that so I had to manually download and run the updater.

**Comment by Hafnernuss** [comment]
I can confirm this, by updating from Update 1 to Update 3 everything works fine.

**Comment by nlohmann** [comment]
Thanks for reporting!
