### PR TITLE
Fix global UDLs

### LINKED ISSUE #3644: _json  operator""()
### Description

had some issues with  `operator"" _json`  namespacing.  added the #define as per docs: https://json.nlohmann.me/api/operator_literal_json/   then there was an issue with #if JSON_USE_GLOBAL_UDLS   not making any sense.  should that be #ifdef ?  

### Reproduction steps

1. #define JSON_USE_GLOBAL_UDLS
2. #if JSON_USE_GLOBAL_UDLS   causes compiler error

### Expected vs. actual results

probaly should be #ifdef,  not #if

### Minimal code example

_No response_

### Error messages

_No response_

### Compiler and operating system

msvc 2019 - 16.11.17 (current as of 2022-08-02)

### Library version

3.11.0

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### LINKED ISSUE #3645: Regression: no matching literal operator for call to 'operator""_json'
### Description

Code I wrote for https://github.com/nlohmann/json/discussions/3594 does no longer compile with the latest 3.11.0 release.

The line in question is 

```cpp
json j;
j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
```

This compiled before, but now fails with

```
example.cpp:261:107: error: no matching literal operator for call to 'operator""_json' with arguments of types 'const char *' and 'unsigned long', and no matching literal operator template
    j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
                                                                                                          ^
```

### Reproduction steps

Compile

```cpp
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main() {
    json j;
    j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
}
```

with version 3.11.0.

### Expected vs. actual results

Expected: compiles without error.

Actual: Error.

### Minimal code example

```Shell
See above.
```

### Error messages

```Shell
example.cpp:7:107: error: no matching literal operator for call to 'operator""_json' with arguments of types 'const char *' and 'unsigned long', and no matching literal operator template
    j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
                                                                                                          ^
```

### Compiler and operating system

Apple Clang 13.1.6 (clang-1316.0.21.2.5), macOS 12.4 (21F79)

### Library version

3.11.0 release version

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by falbrechtskirchinger**
Really default `JSON_GLOBAL_UDLS` to `1` (oops) and modify tests to catch this error.

Fixes #3644.
Fixes #3645.

### CODE REVIEW

**Comment by falbrechtskirchinger** [comment]
As expected, the tests are failing now without the fix.

File: docs/mkdocs/docs/api/operator_literal_json.md [hunk 1]
```diff
@@ -7,16 +7,16 @@ json operator "" _json(const char* s, std::size_t n);
...
 
-Use any of the following lines to bring the operator into scope:
+It is recommended to bring the operator into scope using any of the following lines:
 ```cpp
 using namespace nlohmann::literals;
 using namespace nlohmann::json_literals;
 using namespace nlohmann::literals::json_literals;
 using namespace nlohmann;
 ```
+This is not required but recommended to ease migration to the next major version release of the library.
```
Comment (falbrechtskirchinger) [inline docs/mkdocs/docs/api/operator_literal_json.md:17]: I'm changing this to:
"This is suggested to ease migration ...."

Same in the other file.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Comment by nlohmann** [comment]
Let's wait until the CI succeeds. I would then create a new release with https://github.com/nlohmann/json/discussions/3640 as release notes. Thanks for the quick response! I guess this is another item for https://github.com/nlohmann/json/discussions/3641.

**Comment by falbrechtskirchinger** [comment]
I have one more minor documentation tweak, but I'm waiting for CI to pass.

I'm adding this to the top of the lists of recommended ways to bring the UDL operators into scope:
```cpp
using nlohmann::literals::operator "" _json[_pointer];
```

**Comment by nlohmann** [comment]
> ```c++
> using nlohmann::literals::operator "" _json[_pointer];
> ```

I find the `[]` notation confusing. I guess you mean.

```c++
using nlohmann::literals::operator "" _json;
using nlohmann::literals::operator "" _json_pointer;
```

**Comment by falbrechtskirchinger** [comment]
> Let's wait until the CI succeeds. I would then create a new release with #3640 as release notes. Thanks for the quick response! I guess this is another item for #3641.

Sorry for messing this one up in the first place. Really don't know how it happened. Maybe I forgot to cherry-pick the most important commit...

**Comment by nlohmann** [comment]
> I have one more minor documentation tweak, but I'm waiting for CI to pass.

Unfortunately, GCC 4.8 complains.

**Comment by falbrechtskirchinger** [comment]
> > ```c++
> > using nlohmann::literals::operator "" _json[_pointer];
> > ```
> 
> I find the `[]` notation confusing. I guess you mean.
> 
> ```c++
> using nlohmann::literals::operator "" _json;
> using nlohmann::literals::operator "" _json_pointer;
> ```

Each file gets the correct line. :-)

**Comment by nlohmann** [comment]
> > Let's wait until the CI succeeds. I would then create a new release with #3640 as release notes. Thanks for the quick response! I guess this is another item for #3641.
> 
> Sorry for messing this one up in the first place. Really don't know how it happened. Maybe I forgot to cherry-pick the most important commit...

No problem at all! You contributed so much to this release!

**Comment by falbrechtskirchinger** [comment]
I think I fixed it. Works on Compiler Explorer (GCC 4.8.1).

**Review by nlohmann — APPROVED** [review]
Looks good to me.
