### ISSUE TITLE
Regression: no matching literal operator for call to 'operator""_json'

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#3645]
### Description

Code I wrote for https://github.com/nlohmann/json/discussions/3594 does no longer compile with the latest 3.11.0 release.

The line in question is 

```cpp
json j;
j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
```

This compiled before, but now fails with

```
example.cpp:261:107: error: no matching literal operator for call to 'operator""_json' with arguments of types 'const char *' and 'unsigned long', and no matching literal operator template
    j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
                                                                                                          ^
```

### Reproduction steps

Compile

```cpp
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main() {
    json j;
    j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
}
```

with version 3.11.0.

### Expected vs. actual results

Expected: compiles without error.

Actual: Error.

### Minimal code example

```Shell
See above.
```

### Error messages

```Shell
example.cpp:7:107: error: no matching literal operator for call to 'operator""_json' with arguments of types 'const char *' and 'unsigned long', and no matching literal operator template
    j = R"({ "1": 1, "2": [ 1, 2, 3, 4, 5], "3": "third-value", "4": { "4-1": 1, "4-2": 2 }, "5": true })"_json;
                                                                                                          ^
```

### Compiler and operating system

Apple Clang 13.1.6 (clang-1316.0.21.2.5), macOS 12.4 (21F79)

### Library version

3.11.0 release version

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment]
Dang it. You know what helps in finding these issues? Remembering to add the CI target to the workflow. :-(

**Comment by nlohmann** [comment]
I guess there will be a 3.11.1 then :)

**Comment by falbrechtskirchinger** [comment]
Guess so. Working on a fix.

**Comment by nlohmann** [comment]
I was a bit confused that all tests had the namespace for the literals included.

**Comment by falbrechtskirchinger** [comment]
I'm modifying the tests and then I'm going to break it again on purpose. The first PR test run should fail.

**Comment by nlohmann** [comment]
I can confirm adding

```cpp
using namespace nlohmann::json_literals;
```

fixes the error.

**Comment by nlohmann** [comment]
I can confirm that #3646 fixes this issue.
