### ISSUE TITLE
Incompatibility of std::char_traits and std::byte in Xcode 16.3

### ISSUE THREAD

**Issue by figueroa1395** [nlohmann/json#4756]
### Description

When using [nlohmann/json](https://github.com/nlohmann/json/tree/v3.12.0), specifically `nlohmann::ordered_json::from_msgpack()` with an argument (buffer) of the type `std::vector<std::byte>` in some tests within the [power-grid-model repo](https://github.com/PowerGridModel/power-grid-model/tree/main), these fail to compile with Xcode 16.3.

In more detail, we use `c++20` and locally, the build fails for Xcode >=16.3. Specifically the problem arises from [this line](https://github.com/PowerGridModel/power-grid-model/blob/fc123b369cc7de95094da4da7f8c132ee8979a6d/tests/native_api_tests/test_api_serialization.cpp#L86), where `nlohmann::ordered_json::from_msgpack()` is used together with `std::vector<std::byte>`. This issue comes from the fact that `std::char_traits` doesn't natively support types other than `char`, `wchar_t`, `char8_t`, `char16_t`, `char32_t` (see [Xcode 16.3 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16_3-release-notes)), unless some specializations are provided.

Now, in your library, you do provide some specializations in [this place](https://github.com/nlohmann/json/blob/85df7ed59350563c36e39ba999212229ba4bfb1c/include/nlohmann/detail/meta/type_traits.hpp#L191), but there is none compatible with `std::byte`. Furthermore, the use of `std::byte` would make both our and our users' lives easier (which we already supported before the release of Xcode 16.3), so it is desirable that a specialization is included.

For the above reasons, simply using `char` instead is not a solution and, even though we did try to hack this in a [PR](https://github.com/PowerGridModel/power-grid-model/pull/956/files), MSVC really [dislikes it](https://github.com/PowerGridModel/power-grid-model/actions/runs/14493786141/job/40656224096?pr=956). Hence, I would like to request adding the `std::byte` specialization to `std::char_traits`, such that this can easily be used in that way. 

### Reproduction steps

Clone the [power-grid-model repo](https://github.com/PowerGridModel/power-grid-model.git) and try to compile with Xcode 16.3. The [build guide](https://power-grid-model.readthedocs.io/en/stable/advanced_documentation/build-guide.html) may be useful for this. And you would get compilation errors pointing to `nlohmann/json` and `std::char_traits`.

### Expected vs. actual results

Expected is to be able to compile without any issue. Actual results is a compilation error pointing towards `nlohmann/json`.

### Minimal code example

```Shell

```

### Error messages

```Shell

```

### Compiler and operating system

Apple clang version 17.0.0 (clang-1700.0.13.3) and arm64-apple-darwin24.4.0

### Library version

3.12.0

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment]
This sounds plausible. PRs welcome!

**Comment by XueSongTap** [comment]
# Proposal: Adding `std::char_traits<std::byte>` Specialization to nlohmann/json

## Background

Issue #4756 reports a compilation failure when using `nlohmann::ordered_json::from_msgpack()` with `std::vector<std::byte>` in Xcode 16.3 and newer versions. According to Xcode 16.3's release notes, `std::char_traits` only natively supports `char`, `wchar_t`, `char8_t`, `char16_t`, and `char32_t` types, causing compatibility issues with `std::byte`.

## Problem Statement

The nlohmann/json library already provides specializations for `std::char_traits` for various types like `unsigned char` and `signed char` in `detail/meta/type_traits.hpp`, but lacks support for `std::byte`. This causes compilation failures when processing binary data stored in `std::vector<std::byte>` using MessagePack functions.

## Proposed Solution

Add a specialization for `std::char_traits<std::byte>` following the existing pattern for other character type specializations in the library. This will allow seamless use of `std::byte` containers with the library's binary format functions.

## Implementation Details

The implementation will be added to `include/nlohmann/detail/meta/type_traits.hpp` alongside the existing specializations for `unsigned char` and `signed char`. The specialization will:

1. Inherit from `std::char_traits<char>` to maintain consistent behavior
2. Properly handle type conversions between `std::byte` and integer types
3. Implement proper EOF handling for `std::byte` 
4. Include appropriate C++17 conditional compilation guards


## Compatibility Considerations

- The specialization follows the same pattern as other specializations in the library
- No changes to existing code or APIs are required
- The solution should be compatible with all major compilers

## Testing Strategy

1. Create a unit test that attempts to use `from_msgpack()` with `std::vector<std::byte>` data
2. Ensure the solution works with other major compilers (MSVC, GCC, Clang)
3. Confirm the solution resolves the issue reported in the power-grid-model project

Hi @nlohmann @figueroa1395 Could you take a look and let me know if this approach makes sense to you? Any concerns or suggestions before I submit the full PR?

**Comment by nlohmann** [comment]
@XueSongTap Looks good to me. Thanks for the extensive proposal, and a especially for thinking of a unit test!

**Comment by figueroa1395** [comment]
@XueSongTap Looks good to me as well. Feel free to reach out if you need a hand. In addition and for your reference, the implementation part might look like something along the lines of https://github.com/PowerGridModel/power-grid-model/pull/956/files, but of course, in the right place.
