### ISSUE TITLE
can't parse std::vector<std::byte>

### ISSUE THREAD

**Issue by Spongman** [nlohmann/json#2869]
this worked in v2.1.1, but no longer works in v3.9.1:

````c++
int main() {
	std::vector<std::byte> rg;
	nlohmann::json::parse({rg.begin(), rg.end()});
}
````

```
include/nlohmann/nlohmann/json.hpp:5164:40: error: no matching function for call to ‘nlohmann::detail::iterator_input_adapter<const char*>::iterator_input_adapter(nlohmann::detail::iterator_input_adapter_factory<__gnu_cxx::__normal_iterator<std::byte*, std::vector<std::byte> >, void>::adapter_type)’
 5164 |         : ia(input_adapter(first, last)) {}
```

i tried just passing the iterators directly:

```c++
int main() {
	std::vector<std::byte> rg;
	nlohmann::json::parse(rg.begin(), rg.end());
}
```

but this gives a bunch of these:
```
include/nlohmann/nlohmann/json.hpp:7423:59: error: cannot convert ‘char’ to ‘std::byte’ in initialization
 7423 |                 std::array<char_type, 4> true_literal = {{'t', 'r', 'u', 'e'}};
      |                                                           ^~~
      |                                                           |
      |                                                           char
```

**Comment by nlohmann** [comment]
This works on the latest `develop` branch (I did not check 3.9.1):

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

int main()
{
    std::vector<std::byte> rg = {(std::byte)'t', (std::byte)'r', (std::byte)'u', (std::byte)'e'};
    auto j = nlohmann::json::parse(rg.begin(), rg.end());
    std::cout << j << std::endl;
}
```

Output:

```json
true
```

**Comment by Spongman** [comment]
are you going to tag a release containing this fix any time soon? or should i just try to cherry-pick this into 3.9.1?

**Comment by nlohmann** [comment]
It is fixed with https://github.com/nlohmann/json/pull/2550 and will be part of the next release. I do not have a release date, though.

**Comment by nlohmann** [comment]
Duplicate of https://github.com/nlohmann/json/discussions/2546.

**Comment by Spongman** [comment]
i see that 3.9.1 was nearly 11 months ago. would it be possible to have separate branches for bug fixes and new features and prioritize releasing fixes to bugs like this?

**Comment by nlohmann** [comment]
No, I'm sorry I don't have the capacity to do so. `develop` is the bleeding-edge branch, and the next release will be hopefully done soon.

**Comment by nlohmann** [comment]
(I am running this project beside my day job, so I cannot make any promises or guarantees. You can [sponsor](https://github.com/sponsors/nlohmann) my work, though.)
