### ISSUE TITLE
Compiler Switches -Weffc++ & -Wshadow are throwing errors

### ISSUE THREAD

**Issue by LoeFe** [nlohmann/json#1558]
- What is the issue you have?
When Compiling the lib with -Weffc++ & -Wshadow the compiler returns with error

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
Use gcc and compile the code

- What is the expected behavior?
No errors are returned

- And what is the actual behavior instead?
The lib doesn't compile with these switches

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
GCC 4.8.5 on a windows system compiling apps that are running under linux

- Did you use a released version of the library or the version from the `develop` branch?
release

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by nlohmann** [comment]
How did you compile the code? What is the exact error output?

**Comment by LoeFe** [comment]
I used to compile with gcc 7.2.x and changed back to an older one (4.8.5).

But in the meantime I've changed to gcc 8.2.0 and now it works. Sry for that and thanks for your immediate reply.
