### ISSUE TITLE
Compile error in VS2015 when compiling unit-conversions.cpp

### ISSUE THREAD

**Issue by sonulohani** [nlohmann/json#1114]
When i compile unit-conversions.cpp with VS 2015 compiler, I get this error:-

"unit-conversions.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj" . 

I think we should configure this in cmake to compile this file with /bigobj. 

VS 2015 configuration:-
Debug mode
Platform :- x64

Here is the screenshot of the same:-
![issue ss](https://user-images.githubusercontent.com/2958681/40701563-03bc0438-63fc-11e8-89a6-915b08282308.PNG)

**Comment by nlohmann** [comment]
That is strange, because it works on AppVeyor (MSVC 19.0.24215.1) without issue:

- configuration file: https://github.com/nlohmann/json/blob/develop/appveyor.yml
- last output: https://ci.appveyor.com/project/nlohmann/json/build/job/qk7oe3c36hnm0bd3

**Comment by sonulohani** [comment]
I compiled with VS2017 and it's compiling perfectly fine with this. I don't know why its throwing error with VS2015.

**Comment by nlohmann** [comment]
@sonulohani As I never experienced this issue with our CI setup, could you please provide your used MSVC version?

**Comment by sonulohani** [comment]
@nlohmann  sure, I will post the MSVC version by this Monday. Sorry for the delay.

**Comment by sonulohani** [comment]
Hi @nlohmann ,
Here are the version detail of my MSVC 2015 compiler (got it from cmake):-
Selecting Windows SDK version  to target Windows 10.0.15063.
The CXX compiler identification is MSVC 19.0.24215.1

**Comment by nlohmann** [comment]
This is strange - we use exactly this compiler on AppVeyor, see https://ci.appveyor.com/project/nlohmann/json/build/2816/job/48rag9jhyp2je364?fullLog=true.

The difference may be that we build in Release mode. Could you try this please?

**Comment by nlohmann** [comment]
Ok, then we need to set `/bigobj` for Debug builds. Could you please replace `test/CMakeLists.txt` with [CMakeLists.txt](https://github.com/nlohmann/json/files/2137372/CMakeLists.txt) and try building a Debug build?

**Comment by nlohmann** [comment]
@sonulohani Did you have a chance to test the fixed CMakeLists file from https://github.com/nlohmann/json/issues/1114#issuecomment-400313051?

**Comment by sonulohani** [comment]
Hi @nlohmann ,

I have created the PR.

**Comment by nlohmann** [comment]
Fixed with #1151.

Thanks!

**Comment by sonulohani** [comment]
You're welcome
