### ISSUE TITLE
Unknown Type Name clang error when using NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE

### ISSUE THREAD

**Issue by stoeckley** [nlohmann/json#2313]
#### What is the issue you have?

Clang reports:

```
error: unknown type name 's'
```

with this code:

```
struct Foo {
	string s;
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Foo, s)
```
(in the same namespace)

more specifically:

```
main.cpp:24:37: error: unknown type name 's'
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Foo, s)
                                            ^  (the '^' appears under the 's')
main.cpp:26:1: error: expected function body after function declarator
```

Compiled as so:

```clang++ -std=c++17 main.cpp -o build/main -O3```
```
~/projects/jsontest clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
```

#### Which version of the library did you use?

```3.8.0```

- [ ] latest release version 3.7.3
- [X] other release - please state the version: 3.8.0
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [X] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment]
Please try again with the latest `develop` branch. This issue should have been fixed lately.

The following code works with Apple clang version 12.0.0 (clang-1200.0.22.19).

```cpp
#include <iostream>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

struct Foo {
    std::string s;
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Foo, s)

int main()
{
    Foo foo;
    foo.s = "Hello, world!";
    
    json j = foo;
    std::cout << j << std::endl;
}
```

Output:

```json
{"s":"Hello, world!"}
```

**Comment by stoeckley** [comment]
You are correct!! Thanks.
